

services:
  backend:
    build:
      context: ./Java-Quiz
      dockerfile: Dockerfile
    container_name: quizbuilder-backend
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - quiznet

  frontend:
    build:
      context: ./user_interface
      dockerfile: Dockerfile
    container_name: quizbuilder-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - quiznet

networks:
  quiznet:
    driver: bridge
